
ASSETS = [
"EURUSD","GBPUSD","USDJPY","AUDUSD","USDCAD","USDCHF","NZDUSD","EURJPY","GBPJPY","EURGBP",
"BTCUSDT","ETHUSDT","BNBUSDT","SOLUSDT","XRPUSDT","ADAUSDT","DOGEUSDT","AVAXUSDT","LINKUSDT","MATICUSDT",
"SPX","NAS100","DJI","DAX","FTSE","GOLD","SILVER","OIL",
"EURCHF","EURAUD","GBPAUD","AUDJPY","CADJPY","CHFJPY","NZDJPY","AUDNZD","GBPCAD","EURCAD","EURNZD","GBPNZD"
]

MAX_DAILY_CREDITS = 600
TIMEFRAME = "1min"
