import os

ASSETS = [
    "EURUSD","GBPUSD","USDJPY","AUDUSD","USDCAD","USDCHF","NZDUSD","EURJPY","GBPJPY","EURGBP",
    "BTCUSDT","ETHUSDT","BNBUSDT","SOLUSDT","XRPUSDT","ADAUSDT","DOGEUSDT","AVAXUSDT","LINKUSDT","MATICUSDT",
    "SPX","NAS100","DJI","DAX","FTSE","GOLD","SILVER","OIL",
    "EURCHF","EURAUD","GBPAUD","AUDJPY","CADJPY","CHFJPY","NZDJPY","AUDNZD","GBPCAD","EURCAD","EURNZD","GBPNZD"
]

TIMEFRAME = "1min"

# CHAVES DA TWELVE VINDO DO RENDER
TWELVE_API_KEYS = [
    os.getenv("TWELVE_API_KEY_1", "").strip(),
    os.getenv("TWELVE_API_KEY_2", "").strip(),
]
TWELVE_API_KEYS = [k for k in TWELVE_API_KEYS if k]

# LIMITES INTERNOS DE SEGURANÇA
TWELVE_DAILY_SOFT_LIMIT_PER_KEY = int(os.getenv("TWELVE_DAILY_SOFT_LIMIT_PER_KEY", "300"))
TWELVE_MINUTE_LIMIT_PER_KEY = int(os.getenv("TWELVE_MINUTE_LIMIT_PER_KEY", "6"))
TWELVE_GLOBAL_DAILY_HARD_STOP = int(os.getenv("TWELVE_GLOBAL_DAILY_HARD_STOP", "600"))

# CACHE
CACHE_TTL_1MIN = int(os.getenv("CACHE_TTL_1MIN", "55"))
CACHE_TTL_5MIN = int(os.getenv("CACHE_TTL_5MIN", "295"))

# MODOS DE ECONOMIA
ECONOMY_MODE_AFTER_TOTAL = int(os.getenv("ECONOMY_MODE_AFTER_TOTAL", "500"))
FREEZE_TWELVE_AFTER_TOTAL = int(os.getenv("FREEZE_TWELVE_AFTER_TOTAL", "600"))
