import os

CRYPTO_ASSETS = ["BTCUSDT", "ETHUSDT", "BNBUSDT", "SOLUSDT", "XRPUSDT"]

FOREX_ASSETS = [
    "EURUSD", "GBPUSD", "USDJPY", "AUDUSD", "USDCAD",
    "USDCHF", "NZDUSD", "EURJPY", "GBPJPY", "EURGBP"
]

METALS_ASSETS = ["GOLD", "SILVER"]

ASSETS = CRYPTO_ASSETS + FOREX_ASSETS + METALS_ASSETS

SCAN_INTERVAL_SECONDS = int(os.getenv("SCAN_INTERVAL_SECONDS", "60"))
TWELVE_SCAN_INTERVAL_SECONDS = int(os.getenv("TWELVE_SCAN_INTERVAL_SECONDS", "600"))
TWELVE_BATCH_SIZE = int(os.getenv("TWELVE_BATCH_SIZE", "1"))

TWELVE_API_KEYS = [os.getenv("TWELVE_API_KEY_1", "").strip(), os.getenv("TWELVE_API_KEY_2", "").strip()]
TWELVE_API_KEYS = [k for k in TWELVE_API_KEYS if k]

FINNHUB_API_KEY = os.getenv("FINNHUB_API_KEY", "").strip()
ALPHA_VANTAGE_API_KEY = os.getenv("ALPHA_VANTAGE_API_KEY", "").strip()

TWELVE_DAILY_SOFT_LIMIT_PER_KEY = int(os.getenv("TWELVE_DAILY_SOFT_LIMIT_PER_KEY", "40"))
TWELVE_MINUTE_LIMIT_PER_KEY = int(os.getenv("TWELVE_MINUTE_LIMIT_PER_KEY", "1"))
TWELVE_GLOBAL_DAILY_HARD_STOP = int(os.getenv("TWELVE_GLOBAL_DAILY_HARD_STOP", "60"))

CACHE_TTL_1MIN = int(os.getenv("CACHE_TTL_1MIN", "58"))
CACHE_TTL_5MIN = int(os.getenv("CACHE_TTL_5MIN", "295"))

ECONOMY_MODE_AFTER_TOTAL = int(os.getenv("ECONOMY_MODE_AFTER_TOTAL", "30"))
FREEZE_TWELVE_AFTER_TOTAL = int(os.getenv("FREEZE_TWELVE_AFTER_TOTAL", "60"))

FINNHUB_PAUSE_SECONDS = int(os.getenv("FINNHUB_PAUSE_SECONDS", "120"))
ALPHA_PAUSE_SECONDS = int(os.getenv("ALPHA_PAUSE_SECONDS", "180"))

MAX_SIGNALS = 2


DEFAULT_PAYOUT = float(os.getenv("DEFAULT_PAYOUT", "0.80"))
DEFAULT_RISK_PCT = float(os.getenv("DEFAULT_RISK_PCT", "0.01"))
EXECUTION_DELAY_CANDLES = int(os.getenv("EXECUTION_DELAY_CANDLES", "0"))

EDGE_PROOF_MIN_TRADES = int(os.getenv("EDGE_PROOF_MIN_TRADES", "60"))
EDGE_SEGMENT_MIN_TRADES = int(os.getenv("EDGE_SEGMENT_MIN_TRADES", "15"))

ADAPTIVE_MIN_TRADES = int(os.getenv("ADAPTIVE_MIN_TRADES", "30"))
ADAPTIVE_STRONG_MIN_TRADES = int(os.getenv("ADAPTIVE_STRONG_MIN_TRADES", "80"))
ADAPTIVE_PROVEN_MIN_TRADES = int(os.getenv("ADAPTIVE_PROVEN_MIN_TRADES", "150"))

ALPHA_HIVE_MODE = os.getenv("ALPHA_HIVE_MODE", "validation").strip().lower()


EDGE_GUARD_ACTIVE = os.getenv("EDGE_GUARD_ACTIVE", "1").strip().lower() not in ("0", "false", "no")
EDGE_MIN_PROFIT_FACTOR = float(os.getenv("EDGE_MIN_PROFIT_FACTOR", "1.10"))
EDGE_SEGMENT_MIN_PROFIT_FACTOR = float(os.getenv("EDGE_SEGMENT_MIN_PROFIT_FACTOR", "1.03"))
EDGE_LIVE_MIN_PROB = float(os.getenv("EDGE_LIVE_MIN_PROB", "0.80"))
EDGE_VALIDATION_MIN_PROB = float(os.getenv("EDGE_VALIDATION_MIN_PROB", "0.60"))
EDGE_RECENT_WINDOW = int(os.getenv("EDGE_RECENT_WINDOW", "20"))
EDGE_RECENT_KILL_WINDOW = int(os.getenv("EDGE_RECENT_KILL_WINDOW", "12"))
EDGE_RECENT_KILL_EXPECTANCY_R = float(os.getenv("EDGE_RECENT_KILL_EXPECTANCY_R", "-0.08"))
EDGE_RECENT_WARN_EXPECTANCY_R = float(os.getenv("EDGE_RECENT_WARN_EXPECTANCY_R", "-0.02"))


TRADER_COUNCIL_ACTIVE = os.getenv("TRADER_COUNCIL_ACTIVE", "1").strip().lower() not in ("0", "false", "no")
TRADER_COUNCIL_SPECIALIST_LIMIT = int(os.getenv("TRADER_COUNCIL_SPECIALIST_LIMIT", "36"))
TRADER_COUNCIL_MEMORY_MIN_CASES = int(os.getenv("TRADER_COUNCIL_MEMORY_MIN_CASES", "6"))


BOOTSTRAP_ACTIVE = os.getenv("BOOTSTRAP_ACTIVE", "1").strip().lower() not in ("0", "false", "no")
BOOTSTRAP_MIN_CONFIDENCE = int(os.getenv("BOOTSTRAP_MIN_CONFIDENCE", "69"))
BOOTSTRAP_MIN_SCORE = float(os.getenv("BOOTSTRAP_MIN_SCORE", "2.00"))
BOOTSTRAP_MAX_TRADES = int(os.getenv("BOOTSTRAP_MAX_TRADES", "20"))
BOOTSTRAP_WARMUP_MAX_TRADES = int(os.getenv("BOOTSTRAP_WARMUP_MAX_TRADES", "60"))
BOOTSTRAP_STAKE_MULTIPLIER = float(os.getenv("BOOTSTRAP_STAKE_MULTIPLIER", "0.12"))
BOOTSTRAP_WARMUP_STAKE_MULTIPLIER = float(os.getenv("BOOTSTRAP_WARMUP_STAKE_MULTIPLIER", "0.20"))
